# ============================================================================
# KUBERNETES SECRET TEMPLATE - API KEYS
# ============================================================================
# This template defines a Kubernetes Secret that stores API keys securely.
# Replace the placeholder values with your specific API keys.

apiVersion: v1
kind: Secret
metadata:
  name: openai-secret  # You can rename this to match your API provider
  # You can add additional metadata like annotations here
type: Opaque  # Opaque type is used for arbitrary key-value pairs
stringData:  # stringData allows you to provide non-base64 encoded values
  # Add your API keys here
  OPENAI_API_KEY: "your-key-here"  # Replace with your actual API key. You could also use another AI API. I just happened to use OpenAI
