# ============================================================================
# KUBERNETES SECRET TEMPLATE - DOCKER REGISTRY CREDENTIALS
# ============================================================================
# This template defines a Kubernetes Secret that stores Docker registry credentials.
# These credentials are used to pull images from private registries.

apiVersion: v1
kind: Secret
metadata:
  name: regcred  # You can rename this to match your registry
  namespace: default  # Change to your target namespace if different
type: kubernetes.io/dockerconfigjson  # Special type for Docker registry credentials
data:
  .dockerconfigjson: <base-64-encoded-secret>  # TEMPLATE: Replace with your actual encoded credentials
